### PR TITLE
Maxphiser 

### PR DESCRIPTION
**Pull request by HITVICKY**
git clone https://github.com/HITVICKY/MaxPhisher

cd MaxPhisher

pip3 install -r files/requirements.txt

python3 maxphisher.py

### CODE REVIEW

**Comment by HITVICKY** [comment]
python3 maxphisher.py

**Comment by HITVICKY** [comment]
HITVICKY

**Comment by HITVICKY** [comment]
Maxphiser

**Comment by HITVICKY** [comment]
www.github.com

**Comment by HITVICKY** [comment]
https://github.com/HITVICKY/HITVICKY/pull/1#issue-1574294532

**Review by NIK2323NIK — COMMENTED** [review]
Akkauntingiz xaf ostida

**Review by 6ixoo-cell — COMMENTED** [review]
I'm I just came to check on you

**Pull request merged**
